# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Google
version:      0.62
version_from: lib/Net/Google.pm
installdirs:  site
requires:
    Carp:                          0
    Cwd:                           0
    LWP::Protocol::file:           0
    SOAP::Lite:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
